from twoFA import TwoFactorAuth

# Example secret key
secret_key = "SRAYT6T44HMH6EEIWPWY7RBRZBDJN346"

# Example TOTP token generated by the authentication app
user_token = input("Enter the TOTP token: ")

# Verify the token
is_valid = TwoFactorAuth.verifyToken(secret_key, user_token)

if is_valid:
    print("Token is valid. Access granted.")
else:
    print("Token is invalid. Access denied.")
